server:
    port: 8888 #启动端口
spring:
    application:
        name: ospConfig
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/dzhh/config-repo.git